### ISSUE TITLE
Sprint 1 - Se tiene un modelo entidad-relación aprobado por el equipo - Nota: Para el día miercoles 24-08, nos reuniremos para avanzar en el modelo de entidad - relación y definir nombre que llevaran las tablas y atributos

### ISSUE THREAD

**Issue by JRicardoLeon** [TatianaOspi/Parcking-App#1]

**Comment by TatianaOspi** [comment]
Se avanza con la creación de los atributos y algunos metodos, para el viernes 26 asignaremos una tutoria para aclarar el tema de las relaciones.

**Comment by TatianaOspi** [comment]
Se aprueba el modelo de Proyecto Vehículo para dar inicio a la creación de entidades desde VCS y Tablas en Base de datos
