### ISSUE TITLE
Sprint 1 - Viernes 26-08 Creación de la Base de datos, con sus tablas y atributos, la actividad la realizaremos en vivo para poder soportarnos en caso de presentar alguna inquietud.

### ISSUE THREAD

**Issue by JRicardoLeon** [TatianaOspi/Parcking-App#2]

**Comment by TatianaOspi** [comment]
Se da inicio a la creación de Carpetas desde (C:) CMD carpetas de APP y entidades en desde VSC

**Comment by TatianaOspi** [comment]
Se acuerda con el equipo que @JRicardoLeon realizara la corrección sobre el error que se presenta al momento de compilar, también realizará la creación de las tablas en Bdt´s, la entrega se debe realizar a más tardar el día 31/08/2022 dado que para ese día tenemos la entrega del primer Sprint.

**Comment by TatianaOspi** [comment]
@JRicardoLeon No comparte el proyecto con las correcciones y entrega de Base de Datos, para que cada uno de los integrantes realicemos el mismo ejercicio de enlazar.
